- clean:
    - "~"
- shell:
    - "git submodule update --init --recursive"
- link:
    ~/.aliases.d: aliases.d
    ~/bin: bin
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
